### ISSUE TITLE
Administration utilities not accessible at smaller window sizes

### ISSUE THREAD

**Issue by arouinfar** [phetsims/website#106]
The Administration, Edit Profile, and Sign Out links at the top of the banner are not clickable if the browser width is too narrow. @aaronsamuel137 has suggested that this issue is due to the layering.

**Comment by aaronsamuel137** [comment]
This should be fixed now. Assigning to @arouinfar for review.

**Comment by arouinfar** [comment]
I'm still experiencing the issue. I first tested it in Chrome (my usual browser), and made sure to refresh the page a few times. Then I switched to Firefox. The dev site was not in my Firefox history, but I still refreshed.  The links are only clickable to the right of the red line. For example, if I hover over the A in Administration the link is not clickable, but if I hover over the n, I can click on the link.
![assignment submission-v2-09](https://cloud.githubusercontent.com/assets/8419308/6909036/92183612-d6ff-11e4-8a09-587970d45b0a.png)

Reassigning to @aaronsamuel137.

**Comment by aaronsamuel137** [comment]
Sorry, I forgot to mention that I fixed this on the main website, but not yet on phet-dev. It'll be fixed on phet-dev soon when I merge master back into the new sim branch. Let me know if it works on the main website for you.

**Comment by arouinfar** [comment]
Sorry for the misunderstanding! I've tested it out on the main site, and things appear to be working properly. I'll leave the issue open until the changes make their way to phet dev too.

**Comment by aaronsamuel137** [comment]
OK changes should be on phet-dev now. Assigning to @arouinfar for review.
