### ISSUE TITLE
Error translating Users section in PhET Website Translation #114 (vi)

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/website#237]
Log message:

```java
java.lang.NullPointerException
	at edu.colorado.phet.website.translation.TranslateEntityPanel$2.run(TranslateEntityPanel.java:228)
	at edu.colorado.phet.website.util.hibernate.HibernateUtils.wrapTransaction(HibernateUtils.java:550)
	at edu.colorado.phet.website.translation.TranslateEntityPanel.isStringUpToDate(TranslateEntityPanel.java:218)
	at edu.colorado.phet.website.translation.TranslateEntityPanel$1.populateItem(TranslateEntityPanel.java:158)
	at org.apache.wicket.markup.html.list.ListView.onPopulate(ListView.java:562)
	at org.apache.wicket.markup.repeater.AbstractRepeater.onBeforeRender(AbstractRepeater.java:131)
	at org.apache.wicket.Component.internalBeforeRender(Component.java:1065)
	at org.apache.wicket.Component.beforeRender(Component.java:1099)
	at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1753)
	at org.apache.wicket.Component.onBeforeRender(Component.java:3940)
	at edu.colorado.phet.website.translation.TranslateEntityPanel.onBeforeRender(TranslateEntityPanel.java:288)
```

**Comment by aaronsamuel137** [comment]
Not sure what is going on here, and not sure when I'll have time to look at this. Feel free to take a look if you want @zepumph.

**Comment by aaronsamuel137** [comment]
To reproduce, go to "translate the website" and click on translation 114. Then click on the "Users" tab to translate the Users section. You'll get an Internal Server Error.

**Comment by zepumph** [comment]
From discussion with @aaronsamuel137 

The null pointer is probably happening because of entity keys without entries in the database and vise vera. After doing some investigating VI#114 was getting a null pointer when querying register.gradeHeader, where register.gradesHeader is the key in the database, probably a typo.

After talking about these errors and looking into orphaned strings, we decided to:
Fix orphaned strings/ entities
Add a delete string element to the Manually add an English string form for admins.
Fix translateEntityPanel.java line 228 to log if there is a null pointer to help catch these orphaned strings.

**Comment by zepumph** [comment]
I forgot the issue number in this commit sorry. I fixed most if not all of the orphaned strings in this commit: 059c67f7199e34fd042a77a97ea3c58cc117c8a9. 

The users section is no longer giving a null pointer now, and although I did only limited testing. I believe this problem is solved.

**Comment by oliver-phet** [comment]
Email from translator received yesterday:
Hi Oliver,
The "user page" error is not fixed! I can't translate this page. Please review it.
Best,

**Comment by zepumph** [comment]
This is fixed on master, and will be on phet production when deployed by @aaronsamuel137 tonight.

**Comment by zepumph** [comment]
Fixed on the main website: see https://phet.colorado.edu/?wicket:bookmarkablePage=:edu.colorado.phet.website.translation.TranslationEditPage&translationId=114&translationLocale=vi

Closing
