### ISSUE TITLE
Endless loop of entering and deleting Related Sims

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#385]
@mattpen please read this issue and if it's a quick fix, can you do it? It's currently blocking me from completing #134, and I'd like to get it done soon.

As is, the website has logic for the "Related Sims" category where if two sims are related to each other, removing one as being related will remove the other as being related. So right now, as an example, Area Builder and Arithmetic are related to each other, and have each other listed on their pages. So if I go to the admin page for Area Builder and remove Arithmetic as being related, the website will automatically remove Area Builder from Arithmetic's page.

Now before I go any further explaining this issue, it is very important to note that when adding or removing related sims in the admin page, you can choose between an HTML version or a legacy version (the HTML version has a suffix to denote it). **However**, these two choices are seemingly not differentiated. Regardless of if I choose the one with or without the suffix, the sim page will always present it as the HTML version:

The Admin page's Related Sims for Area Builder:
![areabuilderadmin](https://cloud.githubusercontent.com/assets/5863899/13062807/7b3503ba-d3fe-11e5-919b-4cabdbc2b7ed.PNG)

How it's presented:
![areabuilderpage](https://cloud.githubusercontent.com/assets/5863899/13062823/a5e178dc-d3fe-11e5-8151-0101a1db040e.PNG)

Clearly this is an issue in and of itself, but leads me to the blocking issue, described here.
Let's say I see the above, and go to the admin page for Area Builder and delete the non-HTML sim from the Related Sims table. Well guess what this does? As I described in the first paragraph, deleting that second Arithmetic from Area Builder will *also* delete Area Builder from Arithmetic. So now I'm left with Arithmetic not being related to Area Builder (which I want). So to fix this I would go to the admin page for Arithmetic and add Area Builder, except....

The logic I described in the first paragraph also applies in the reverse. If I go to the admin page for Arithmetic and ADD Area Builder as a related sim, the website will automatically add Arithmetic to Area Builder...and I end up right back to where I started with Area Builder having two Arithmetics listed. I'm in an endless loop, and it would be great if the site did not add that second sim back to Area Builder. Now note that I would add "Area Builder (HTML)" to Arithmetic (HTML), and since "Arithmetic (HTML)" is already in the list for Area Builder (HTML), it automatically adds the non HTML-suffix version to the list of related sims.

Phew..that was a long one...if this didn't clarify anything for you @mattpen, skype me.

**Comment by amanda-phet** [comment]
@mattpen do you have time to look at this issue?

**Comment by mattpen** [comment]
@amanda-phet @phet-steele 

I deployed a fix to [phet-new](https://phet-new.colorado.edu/en/simulation/area-builder).  I have blocked legacy sims from being displayed as related sims if there is a related HTML sim.  We will need to retain the relation between the legacy sims.  When viewing the page in a non-english locale, the website looks first for a translated HTML sim in the locale, then a translated Legacy sim in the locale, and only falls back to English if neither of those are found.  [(See Area Builder in ar_SA for example)](https://phet-new.colorado.edu/ar_SA/simulation/area-builder#related-sims-header)  I'm not sure if this behavior is still desired, if not I can separate the link entirely.

Can either of you take a look and let me know if the behavior matches expectations?

**Comment by phet-steele** [comment]
@mattpen the legacy fix is working great, thanks! But the real stickler of this issue remains (I just tried on phet-new) and here's a flowchart of what happened. The underlined sim is the sim page, with the sims listed below being which sims appear in the "Related Simulations" header:
<img width="657" alt="screen shot 2016-07-25 at 11 25 53 am" src="https://cloud.githubusercontent.com/assets/5863899/17110623/1b51eda6-525b-11e6-8734-149ff427ab05.png">

The green "Add" step is the only thing I did. The red steps were all done automatically by the website as a result of the green "Add". This results in an incorrect listing of sims in pH Scale (it lists pH Scale: Basics twice).

**Comment by mattpen** [comment]
@phet-steele - I could not recreate this behavior on phet-new.  Which server did you try this on?  I'm assuming you mean the HTML5 version of pH: Scale, but please specify.

**Comment by phet-steele** [comment]
Yes phet-new, and yes HTML5 of everything.

**Comment by mattpen** [comment]
@phet-steele - I don't think it is possible to achieve the starting state that you proposed in the diagram any longer, this must have been a legacy flaw.  Since our current state is accurate (according to https://github.com/phetsims/website/issues/134), then any changes you make will leave us in a correct state. Closing.
