### ISSUE TITLE
Translations of 'About' section are not being published.

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#397]
The es_PE translator notified us that the 'About' section is not showing translated strings even when all of the section's strings have been translated. See:

http://phet.colorado.edu/es_PE/about

**Comment by mattpen** [comment]
@oliver-phet - Is the translator able to reach the About section of the tranlsate utility?  It looks like he's translated nearly everything except the About page:

![image](https://cloud.githubusercontent.com/assets/11747676/13605831/acdf7b5c-e506-11e5-8b20-088f30284e3a.png)


I can't even get to the translate page for About, I'm getting an error.

```Mixed Content: The page at 'https://phet.colorado.edu/?wicket:bookmarkablePage=:edu.colorado.phet.website.translation.TranslationEditPage&translationId=21&translationLocale=es' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js'. This request has been blocked; the content must be served over HTTPS.```

**Comment by mattpen** [comment]
Also, most of the strings on this page are not using the translatable versions, but are just plain text.  I'm assuming that is not by design?

**Comment by oliver-phet** [comment]
I would assume the translator was able to reach the About section since most of the strings are translated.

> Also, most of the strings on this page are not using the translatable versions, but are just plain text. I'm assuming that is not by design?

I don't know what you mean here by translatable versions. Do you mean the website isn't using the translated string when displaying the About page in another locale?

**Comment by mattpen** [comment]
@oliver-phet - The main About page is basically not translatable, whenever the last update was made it was implemented with plain text instead of translatable strings.  Do you know if this was a design choice?

**Comment by oliver-phet** [comment]
I don't remember that being the design choice. I know that the team page was not to be translated. @ariel-phet Do you know why the 'About' section of the site is not translatable?

**Comment by ariel-phet** [comment]
There is no reason for the "About" section to not be translatable -- it is pretty rare we do not make something translatable (such as licensing).

**Comment by mattpen** [comment]
@oliver-phet - The translatable About page has been published on phet-dev.  I can publish this on figaro on the next deploy.  Does everything look ok now?

**Comment by oliver-phet** [comment]
I'm looking on phet-dev, but none of the sections on the About page are translated, so it doesn't appear to be fixed?

**Comment by mattpen** [comment]
@oliver-phet - I deployed a different branch after posting this, sorry.  I'll put it up on phet-dev later today.

**Comment by mattpen** [comment]
@oliver-phet - It should be back up now.

**Comment by oliver-phet** [comment]
@mattpen I'm still seeing quite a few untranslated strings. See this: http://phet-dev.colorado.edu/es_PE/about

It seems like some of the strings on that page aren't able to be translated. Translation es_PE #971 has almost all of the strings translated, but there is a lot of English still showing up on that page?

**Comment by mattpen** [comment]
@oliver-phet  Translation #971 has 2 out-of-date and 39 untranslated strings for the About page on phet-dev. Are you looking at the translation on figaro?  The only two that should be translated are the first paragraph and the main video header. The rest are new and aren't available to translators on figaro yet.  I could sub in some Google translate strings (on phet-dev only) if you want to see how it will look.

**Comment by oliver-phet** [comment]
Ah, understood. In that case this is OK to push!

**Comment by mattpen** [comment]
@oliver-phet - This was deployed to figaro tonight.  Can you check with the es_PE translator and make sure that he is able to edit this page now?

**Comment by oliver-phet** [comment]
Translator contacted. Will re-open if needed.
